language: python
python:
- '2.7'
addons:
  postgresql: "9.4"
sudo: false
env:
  global:
  - DATABASE_URL=postgres://postgres@localhost:5432/brambling_test
  - PIPENV_IGNORE_VIRTUALENVS=1
cache:
  pip: true
  directories:
  - $HOME/.cache/pipenv
install:
- pip install pipenv
- pipenv --version
- pipenv install --ignore-pipfile
- pipenv graph
- psql --version
- pipenv run pip install flake8==3.3.0
before_script:
- psql -c 'drop database if exists brambling_test;' -U postgres
- psql -c 'create database brambling_test;' -U postgres
- pipenv run flake8 brambling
script:
- python -c "from pipenv.environments import user_cache_dir; print user_cache_dir('pipenv')"
- pipenv run python -c "import django; print django.VERSION"
- "pipenv run ./manage.py test --verbosity=2 brambling"
notifications:
  slack:
    secure: U8uCS43H0wmkkolDc2VLdwN+vJTxfZtjP/1tHKejUGD6BKWJ5uKBjUjZFpy4O8FcfKkpybSobkK9bgo8/5UV9fi01/Ybli5oBp6gBQARQUKtzFBzLtSGReD5QHa/ezFcoFlxHkCFOZe4oZc/C2+l/x8IyaXxeB3pQvlFeKP+PSw=
    on_success: change
    on_failure: always
    on_start: never
