language: python
python:
- '2.7'
sudo: false
env:
- DATABASE_URL=postgres://postgres@localhost:5432/brambling_test
cache: pip
install:
- pip install . --no-deps
- pip install --no-deps -r requirements.txt
- if [ $DATABASE_URL == 'postgres://postgres@localhost:5432/brambling_test' ]; then pip install --no-deps psycopg2==2.5.3;
  fi
- pip install flake8
before_script:
- if [ $DATABASE_URL == 'postgres://postgres@localhost:5432/brambling_test' ]; then psql -c 'drop database if exists brambling_test;'
  -U postgres; fi
- if [ $DATABASE_URL == 'postgres://postgres@localhost:5432/brambling_test' ]; then psql -c 'create database brambling_test;' -U postgres;
  fi
- "flake8 --ignore=E501 brambling"
script:
- "./manage.py test --verbosity=2 brambling"
notifications:
  slack:
    secure: U8uCS43H0wmkkolDc2VLdwN+vJTxfZtjP/1tHKejUGD6BKWJ5uKBjUjZFpy4O8FcfKkpybSobkK9bgo8/5UV9fi01/Ybli5oBp6gBQARQUKtzFBzLtSGReD5QHa/ezFcoFlxHkCFOZe4oZc/C2+l/x8IyaXxeB3pQvlFeKP+PSw=
    on_success: change
    on_failure: always
    on_start: never
